# Generated by Django 4.2.3 on 2023-07-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="review",
            name="text",
            field=models.CharField(default="text_filler", max_length=200),
        ),
    ]
