# Generated by Django 4.2.3 on 2023-07-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0003_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="address",
            field=models.CharField(default="address_filler", max_length=200),
        ),
        migrations.AddField(
            model_name="properties",
            name="type",
            field=models.CharField(
                choices=[("a", "Condo"), ("b", "House")], default="a", max_length=1
            ),
        ),
    ]
