# Generated by Django 4.2.3 on 2023-07-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0005_properties_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
